TeskaLabs/asab-maestro-library

Site/ASAB Maestro/Files/nginx/conf.d/server_https.conf

Added to each location inside remote control nginx tech

General WS conf does not work

---

Site/ASAB Maestro/Descriptors/grafana.yaml
Site/ASAB Maestro/Versions/v23.42.yaml

trying to add introspection I thought I would just copy the same setting as for kibana, but it does not work, yet.
if I manage to finish auth, I would like to have a look at the provisioning - it looks like this could be a great place where to add default dashboards

Draft: Grafana authorization

---

Site/ASAB Maestro/Descriptors/kibana.yaml
Site/ASAB Maestro/Versions/v23.47.yaml

Depends on TeskaLabs/seacat-auth#281

Update Seacat Auth config for Kibana

---

Site/ASAB Maestro/Descriptors/nginx.yaml
Site/ASAB Maestro/Files/nginx/sherpa/webapp-dist.sh

```
/sherpa/webapp-dist.sh: line 96: can't open /sherpa/webapps.dist: no such file
```

Fix nginx and web apps connection

---

Site/ASAB Maestro/Files/seacat-auth/script/mongo-insert.js

closes #37 
chatgpt :) I cannot even pronounce "nullish coalescing operator"

Fix mongo-insert script db.isMaster() does not return boolean but object

---

Site/ASAB Maestro/Descriptors/asab-pyppeteer.yaml
Site/ASAB Maestro/Versions/v24.01.yaml

ASAB Pyppeteer cannot connect to the seacat-auth through service discovery, yet

Fix pyppeteer

---

Site/ASAB Maestro/Descriptors/asab-remote-control.yaml
Site/ASAB Maestro/Files/asab-remote-control/asab-config/Library/__schema__.json
Site/ASAB Maestro/Files/asab-remote-control/asab-config/SMTP/__schema__.json

It allows to edit library and smtp config independently. However, it still does not fit very well into the asab config concept

Split general config to SMTP and Library

---

Site/ASAB Maestro/Files/seacat-auth/script/to_upload/seacat-auth/c.json

More secure admin pswd

---

Site/ASAB Maestro/Descriptors/grafana.yaml
Site/ASAB Maestro/Versions/v24.04.yaml

I don't know whether all the parameters are required @byewokko 
I didn't test it without them.
It probably worked in maestro before, beacause I forgot to assign a version to grafana and latest grafana version was used

Grafana: fix oauth

---

Site/ASAB Maestro/Descriptors/seacat-auth.yaml
Site/ASAB Maestro/Versions/v24.13.yaml
Site/ASAB Maestro/Versions/v24.14.yaml

- new global version `v24.14`
- added missing seacat database name

add missing database name

---

Site/ASAB Maestro/Files/nginx/conf.d/default.conf

We see a lot of websocket timeouts.

Increasing NGINX timeouts.

---

Site/ASAB Maestro/Versions/v24.16.yaml

asab-remote-control: v24.16-beta has changed since last time

Add v24.16

---

Site/ASAB Maestro/Versions/v24.17.yaml

waiting for final UI version
I'll add wrapper config of iris to model:
```
asab-iris:
instances: ["cake1"]
asab:
config:
email:
markdown_wrapper: /Templates/Wrapper/markdown_wrapper.html
```

Global version v24.17

---

Site/ASAB Maestro/Files/nginx/conf.d/default.conf

main to production

---

Site/ASAB Maestro/Descriptors/burrow.yaml

This needs to be added to telegraf configuration. That's quite unlucky
```
[[inputs.burrow]]
servers = ["http://burrow:8001"]
```

Draft: Burrow

---

Site/ASAB Maestro/Descriptors/telegraf.yaml

Removing /snap from disk utilization.

---

Site/ASAB Maestro/Versions/v24.22-beta3.yaml

v24.22-beta3 to be on the same version as lmio-common library.
When merged, I'll create tag from master named v24.22-beta3

Global release v24.22-beta3

---

Site/ASAB Maestro/Files/seacat-auth/script/mongo-insert.js

I forgot a print in the script. 
It could be quite handy in debugging, though. So from a bug, I made a feature.

Fix: mongo sherpa - print

---

Site/ASAB Maestro/Descriptors/asab-iris.yaml

Fix indentation to apply the configuration

---

Site/ASAB Maestro/Versions/v24.22.yaml

Fixes AttributeError when updating credentials.

Patch seacat-auth (credentials update fix)

---

Site/ASAB Maestro/Descriptors/burrow.yaml

Remove unnecessary config from burrow

---

Site/ASAB Maestro/Descriptors/kibana.yaml

Fix discovery of kibana

---

Site/ASAB Maestro/Files/seacat-auth/script/mongo-insert.js

Records in the mongo database that are managed by maestro should be not only created and updated but those that are not in the library anymore should be also deleted. That is tricky as I don't want to delete any other record from the database. And also, some collections use string as id and some ObejctId.

Delete managed records

---

Site/ASAB Maestro/Descriptors/seacat-auth.yaml

- Update tenant config schema based on the changes in UI

Update tenant config schema

---

Site/ASAB Maestro/Files/seacat-auth/script/mongo-insert.js

I hate this script.
I had tested it against already existing installation before. Now, I tried fresh one and the script failed with empty mongo. This helped.

Take care of new collection

---

Site/ASAB Maestro/Descriptors/mongo.yaml

Currently being tested on fusion - if there are no more zombies on fusion in few days, we know where they came from.

The healthcheck might be the source of zombies

---

Site/ASAB Maestro/Descriptors/bs-query.yaml

For new asab auth: reading tenants list

BSQ prepared for new auth

---

Site/ASAB Maestro/Descriptors/seacat-auth.yaml

Refactor upstream configuration

---

Site/ASAB Maestro/Descriptors/asab-config.yaml

Fix asab config configuration and nginx configuration to make export funcitonality work.

Fix asab config download

---

Site/ASAB Maestro/WebApps/LogMan.io WebUI.yaml

- add /lmio_parser_builder_webui: lmio_parser_builder_webui to LogMan.io WebUI.yaml

Update LogMan.io WebUI.yaml

---

Site/ASAB Maestro/Descriptors/influxdb.yaml

Compatible with inlfuxdb tech refactoring in the remote control

Simplify influxdb tech in the remote control by extending the declaration
