TeskaLabs/asab-maestro-library

- Site/ASAB Maestro/Descriptors/asab-iris.yaml
- Site/ASAB Maestro/Versions/v23.21.yaml
All the configuration of asab iris should be filled in as general configuration (smtp, slack, variables)
I don't know how to sort the services into the applications - there is ASAB Maestro application. There should be some more. Where should live descriptors, version files, and how should the model(s) look?
> Adding ASAB Iris

- Site/ASAB Maestro/Descriptors/kibana.yaml
I thought this would be harder, but you already implemented it :grin: 
```
root@lmio-eliska-1:/opt/site/nginx-1# cat conf.d/proxy_caches.conf 
proxy_cache_path /var/cache/nginx/oauth2_introspect_proxy_cache keys_zone=oauth2_introspect:1m max_size=2m;
proxy_cache_path /var/cache/nginx/kibana_proxy_cache keys_zone=kibana:1m max_size=2m;
```
I don't know how to verify it is right - I can open Kibana from UI and when I refresh Kibana I can see request to seacat auth just from time to time, not on every hit. I find it quite good...
> Kibana cache

- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
I forgot to delete the nonsense default config also in seacat auth. And I cannot push to master. And merge without approval. So here it is.
> Secat auth does not need default config

- Site/ASAB Maestro/Descriptors/grafana.yaml
- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
I've decided this is a temporary solution until we have better service discovery. 
In the meantime, I have an internal URL in the model:
```
params:
PUBLIC_URL: "https://maestro.logman.io" 
INTERNAL_URL: "http://lmc01:8890"
```
I guess remote control would be able to create this parameter.
It's not exactly elegant, but dasboards in graphana don't have to wait until we find a nicer solution :)
> Fix grafana auth - Grafana visits sca through internal nginx server

- Site/ASAB Maestro/Descriptors/kibana.yaml
- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
Update descriptors to be compatible with [TeskaLabs/seacat-auth/releases/tag/v23.47-alpha5](https://github.com/TeskaLabs/seacat-auth/releases/tag/v23.47-alpha5)
- Seacat Auth public URL config updated 
- only one public URL is needed, hopefully
- see TeskaLabs/seacat-auth#330
- Seacat Auth config updated in Kibana descriptor
- Config section renamed to `batman:elasticsearch`
- Common ElasticSearch config is loaded from the `elasticsearch` section
- see TeskaLabs/seacat-auth#326 and TeskaLabs/seacat-auth#333
> Seacat Auth update

- Site/ASAB Maestro/Descriptors/asab-pyppeteer.yaml
- Site/ASAB Maestro/Descriptors/bs-query.yaml
- Site/ASAB Maestro/Files/seacat-auth/script/mongo-insert.js
- Site/ASAB Maestro/Versions/v24.01.yaml
TODO:
TODO: Implement Discovery session where needed
> BSQuery and Pyppeteer

- Site/ASAB Maestro/Descriptors/grafana.yaml
- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
- Site/ASAB Maestro/Files/seacat-auth/script/to_upload/seacat-auth/c.json
I used
- secrets in grafana tech,
- params in seacat-auth tech
I removed seacat auth internal location, which is good.
Grafana needs to know an e-mail of the user to authorize them. However, admin does not have an e-mail by default. So I added some nonsense e-mail there and Grafana is happy.
Grafana needs to access public port of seacat auth, because the endpoint is not available on the private port, but it should be, right? @byewokko
> Grafana - oauth without grafana tech

- Site/ASAB Maestro/Descriptors/kafdrop.yaml
tohle typo killne nginx a dologmanovali jsme...
takže prosím rychlý approve
a bohužel to nefunguje ani když opravím typo
> Kafdrop: fix typo

- Site/ASAB Maestro/Files/nginx/conf.d/server_https.conf
@Plesoun This is the "lidová tvořivost".
This oneliner allows adding locations to `/data/hdd/nginx/shared/server_https.d/` manually to allow hybrid installation.
I've just installed lmio-alerts using this feature (even though lmio-alerts service is a great adept for maestro)
> Add hybrid locations

- Site/ASAB Maestro/Descriptors/nginx.yaml
- Site/ASAB Maestro/Files/nginx/conf.d/server_http.conf
- Site/ASAB Maestro/Files/nginx/conf.d/server_https.conf
This is a preparation for the IPv6 support in NGINX.
It moves "listen" directives to descriptor YAML, so that Jinja2 templating can be applied.
TODO: In NGINX tech, `NGINX_LISTEN_IPV6` Jinja2 variable should be set to "1", if there is IPv6 protocol enabled (or configuration explicitly want that.
--- or in model ---
```
define:
type: rc/model
...
params:
NGINX_LISTEN_IPV6: true
```
> NGINX IPv6 support

- Site/ASAB Maestro/Descriptors/jupyter.yaml
- Site/ASAB Maestro/Descriptors/kafdrop.yaml
- Site/ASAB Maestro/Descriptors/kibana.yaml
- Site/ASAB Maestro/Descriptors/zoonavigator.yaml
Seacat-auth mongo content sherpa does insert only - it creates new document only if it does not exists, yet. 
However, in case of clients, this is not very favorable.
If public url changes (it is "localhost" in the very beggining and it needs to be changes by the user in the model) the PUBLIC_URL in the client stayes the same. And redirect does not work.
So, I suggest to make the clients "managed" and do "upsert" - insert and update so the clients are changed whenever PUBLIC_URL changes. However, this is a bit more interactions of the script with mongodb directly. 
Clients should be tagged "managed" in the secat auth also, so they are either not editable fromt he UI at all or the user is at least adviced that their changes will be rewritten by maestro.
OR
Seacat auth will learn to work …
> Fix tools redirects

- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
Users with "admin" role in LMIO could not get through nginx (with 500) and Robin found that the list of the resources is so big for admins that it does not fit into headers.
I did this hotfix in app.logman.io but now we need to find some proper place for this bit.
```
2024/03/05 16:31:11 [error] 36#36: *801 upstream sent too big header while reading response header from upstream, client: 109.81.174.194, server: _, request: "GET /api/seacat-auth/credentials?p=1&i=27 HTTP/2.0", subrequest: "/_oauth2_introspect", upstream: "http://10.17.211.99:8900/nginx/introspect/openidconnect", host: "app.logman.io", referrer: "https://app.logman.io/"
```
> Fix limited request header to make admin role possible

- Site/ASAB Maestro/Descriptors/__commons__.yaml
the same must be in lmio-common library as we still have two __commons__ descriptors :(
> Fix restart policy: we want containers to survive reboot test

- Site/ASAB Maestro/Descriptors/asab-governator.yaml
- Site/ASAB Maestro/Versions/v24.12.yaml
I did not switch to pcr.teskalabs.com, yet as older versions of asab governator are not there and newer version of asab governator is also in docker.teskalabs.com.
So, I'll wait a bit.
> Upgrade to v24.12

- Site/ASAB Maestro/Descriptors/elasticsearch.yaml
- Site/ASAB Maestro/Descriptors/jupyter.yaml
- Site/ASAB Maestro/Descriptors/kafdrop.yaml
- Site/ASAB Maestro/Descriptors/kibana.yaml
- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
- Site/ASAB Maestro/Descriptors/zoonavigator.yaml
Large proxy buffers are only needed for introspection responses, not in the whole server block.
> Increase proxy buffer size in introspection locations only

- Site/ASAB Maestro/Files/zookeeper/confro/zoo.cfg
... addressing this problem:
```
2024-03-25 10:56:37,046 [myid:] - WARN  [NIOServerCxnFactory.AcceptThread:/0.0.0.0:2181:o.a.z.s.RateLogger@87] - Message:Error accepting new connection: Too many connections from /127.0.0.1 - max is 60 Value:null
2024-03-25 10:56:51,938 [myid:] - WARN  [NIOServerCxnFactory.AcceptThread:/0.0.0.0:2181:o.a.z.s.RateLogger@57] - Message: Error accepting new connection: Too many connections from /127.0.0.1 - max is 60
```
*WARNING:* Since Zookeeper works with configurations very weirdly, this likely needs to be changes in governator.bootstrap.
Also - we now a practical case for a need of changing Zookeeper configuration during a cluster life time - this is currently impossible in ASAB Maestro
> Zookeeper max clients - Increase from 60 to 600

- Site/ASAB Maestro/Descriptors/bs-query.yaml
- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
- Simplify mongodb config (https://github.com/TeskaLabs/asab/pull/553)
- Move M2M credentials from bsquery to seacat auth
Compatible with Seacat Auth [v24.06-alpha10](https://github.com/TeskaLabs/seacat-auth/releases/tag/v24.06-alpha10) and later
> Update Seacat Auth config

- Site/ASAB Maestro/Descriptors/elasticsearch.yaml
- Site/ASAB Maestro/Descriptors/telegraf.yaml
- telegraf descriptor adjusted so it can read more than one config file
- elasticsearch can add config into telegraf - I added SOME configuration that did not break telegraf. It needs to be finished in order to collect the data as we desire.
> Add telegraf tech

- Site/ASAB Maestro/Descriptors/grafana.yaml
This fixes login to grafana for users without email address by adding fallback to the subject (sub) userinfo field.
> More failsafe userinfo resolution for Grafana

- Site/ASAB Maestro/Descriptors/influxdb.yaml
closes #21 
180 days retention
it is INIT retention - that means that only new installations and buckets will be affected by this retention setting
> InfluxDB - default retention policy

- Site/ASAB Maestro/Descriptors/asab-iris.yaml
I think I was told to put this configuration to the descriptor. It is slightly weird here and I don't know what happens if the file does not exist. Let's see...
> asab-iris: add markdown wrapper configuration

- Site/ASAB Maestro/Files/mongo/script/mongo-init.js
- Site/ASAB Maestro/Files/seacat-auth/script/mongo-insert.js
I think it worked before only by accident. I improved the way how to decide when to initiate replicaset and when to reconfigure it. Unfortunately, there is no specific check for a mongo instance that is configured to be used in replicaset, but the replicaset has not yet been initiated. In mongo docs, I am advised to initiate the replicaset **only once** but there is no hint how to ensure it. 
I changed the logic **from insert to upsert**. It means that all changes in library get propagated everywhere and it also means pieces from library are **managed** by maestro. @byewokko fyi (is "managed_by" = "maestro" ok?)
> Mongo sherpas refactoring

- Site/ASAB Maestro/Descriptors/mongo.yaml
- Site/ASAB Maestro/Files/mongo/script/mongo-init.js
Before:
```
root@lmio-eliska-1:/opt/site# ./gov.sh compose up mongo-1-init
[+] Running 2/0
✔ Container mongo-1       Running                                                                                                                                                                              0.0s 
✔ Container mongo-1-init  Created                                                                                                                                                                              0.0s 
Attaching to mongo-1-init
mongo-1-init  | Current Mongosh Log ID:	66604bf83ead6d0504baddb3
mongo-1-init  | Using Mongosh:		1.10.6
mongo-1-init  | 
mongo-1-init  | For mongosh info see: https://docs.mongodb.com/mongodb-shell/
mongo-1-init  | 
mongo-1-init  | 
mongo-1-init  | To help …
```
> Mongo: Disable sending telemetry to mongo server

- Site/ASAB Maestro/Files/asab-config/content/script.py
It is common, that asab-config is up and running but zookeeper container is not yet ready, so we want to wait for that as well
```
root@lmio-eliska-1:/opt/site# ./gov.sh compose up asab-config-1-content
[+] Running 2/0
✔ Container asab-config-1          Running                                                                                                                                                                     0.0s 
✔ Container asab-config-1-content  Created                                                                                                                                                                     0.0s 
Attaching to asab-config-1-content
asab-config-1-content  | Upload of config type 'Tools' was not successful. Status: 400. Reason: {'result': 'FAILED', …
```
> Config sherpa: retry in any case

- Site/ASAB Maestro/Descriptors/asab-iris.yaml
- Site/ASAB Maestro/Descriptors/seacat-auth.yaml
- Site/ASAB Maestro/Files/asab-remote-control/asab-config/SMTP/__schema__.json
- Site/ASAB Maestro/Files/nginx/asab-config/Tools/__schema__.json
UI sends empty strings for empty values in the formular.
JSON schema works with empty strings as valid string.
That means that if a user does not fill in the value in the UI, empty string is sent and the validation goes green even though the required value was not filled in by the user.
I have made changes in the ASAB Config code: If field is NOT required and it is empty string, it is removed before validation.
(I cannot remove required fileds. That is not right.)
However, that leaves required fields that are empty strings still passing through the validation.
Thus, I introduced one more condition in the schema (in all the config schemas) - if the string is required, it must be at least 1 character long - that means it cannot be empty string.
I would like to ask mainly Mithun and other …
> All required items must have at least 1 character

- Site/ASAB Maestro/Files/asab-remote-control/asab-config/Library/__schema__.json
If the default value is filled in the schema, it is used if the value is not filled by the user. 
However, if the value is not filled in, we want to keep it empty and ignore the configuration section entirely.
> The CA file is not required. 

- Site/ASAB Maestro/Descriptors/asab-config.yaml
ASAB Config has export functionality, but nginx configuration does not reflect it. 
It is not perfect. The upstream is missing. The export endpoint does not have HA. But at least it is there!
**Once approved, I'll cherry-pick it also to v25.28 release branch.** @language-shprt FYI
The resulting configuration:
```
tladmin@fu01:/opt/site$ cat nginx-1/conf.d/server_https.d/location_asab-config-*
location /api/asab-config-1 {
auth_request /_oauth2_introspect;
auth_request_set $authorization $upstream_http_authorization;
proxy_set_header Authorization $authorization;
rewrite ^/api/asab-config-1/(.*) /$1 break;
proxy_pass http://fu01:8894;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection …
```
> ASAB Config export with no oauth

- Site/ASAB Maestro/WebApps/SeaCat Auth WebUI.yaml
- after a switch from standalone SeaCat Auth WebUI to a MFE like distribution, we need to update the distribution source to deploy the particular WebUI
> Update distribution source for SeaCat Auth WebUI

- Site/ASAB Maestro/Descriptors/burrow.yaml
- Site/ASAB Maestro/Descriptors/kafka.yaml
- Site/ASAB Maestro/Descriptors/zookeeper.yaml
- Site/ASAB Maestro/Descriptors/zoonavigator.yaml
ZOOKEEPER_SERVERS changed from string to list in the remote control to make configuration of telegraf possible and easy.
The string was not suitable for the telegraf config syntax.
> ZOOKEEPER_SERVERS changed from string to list

- Site/ASAB Maestro/Files/grafana/provisioning/dashboards/system/system-level-overview.json
Extended regex for node_id to allow hostnames with "_".
> Grafana - System level Overview - Add underscore to regex for node_id values filter

- Site/ASAB Maestro/Descriptors/mongo.yaml
It works. mongo is happy. It works too much :grimacing: 
Will need to find out how to enter the container. 
```
$ docker exec -it mongo-1 mongosh
Current Mongosh Log ID:	68b5e3a8288d25f1b810ce71
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.6
MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
```
> Mongo: Listen on the internal network only

- Site/ASAB Maestro/Descriptors/grafana.yaml
Grafana UI (seen on fusion) reports these errors:
```
Content-Security-Policy: The page’s settings blocked a worker script (worker-src) at blob:https://fu01.teskalabs.int/08dfa2b4-0557-4696-91c0-5c2a861dd685 from being executed because it violates the following directive: “script-src 'self' 'unsafe-inline' 'unsafe-eval'”
```
```
Firefox can’t establish a connection to the server at wss://fu01.teskalabs.int/grafana/api/live/ws.
```
- Allow blob access in worker-src SCP.
- Add websocket location with necessary headers.
> Fix Grafana CSP and WS
